<a href="https://colab.research.google.com/github/walunjab09/Checkgitconnection/blob/main/Word_embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [3]:
### Vocabulary size
voc_size=10000

In [4]:
# One hot representation of sentences (each word is replaced by its position in selected vocabulary):
onehot_repr = [one_hot(word,voc_size) for word in sent]
onehot_repr

[[4186, 1265, 5868, 8135],
 [4186, 1265, 5868, 6321],
 [4186, 674, 5868, 9169],
 [6171, 7829, 8611, 7694, 4638],
 [6171, 7829, 8611, 7694, 5878],
 [2216, 4186, 6673, 5868, 5409],
 [6506, 1228, 7278, 7694]]

In [6]:
# Word embedding
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [7]:
# Making same length for each sentence
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4186 1265 5868 8135]
 [   0    0    0    0 4186 1265 5868 6321]
 [   0    0    0    0 4186  674 5868 9169]
 [   0    0    0 6171 7829 8611 7694 4638]
 [   0    0    0 6171 7829 8611 7694 5878]
 [   0    0    0 2216 4186 6673 5868 5409]
 [   0    0    0    0 6506 1228 7278 7694]]


In [8]:
# Selecting number of dimensions to be shown for each word
dim = 10

In [10]:
# Creating ANN with an Embedded layer
model = Sequential()
model.add(Embedding(voc_size, dim, input_length = sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [12]:
# Converting each word to a vector of length 8 (user defined)
model.predict(embedded_docs)

array([[[ 1.87965371e-02,  1.22520924e-02,  4.40502167e-03,
         -1.03689656e-02,  9.05285031e-03, -2.31193900e-02,
         -1.62391178e-02,  2.01234706e-02,  1.25450008e-02,
          1.22347362e-02],
        [ 1.87965371e-02,  1.22520924e-02,  4.40502167e-03,
         -1.03689656e-02,  9.05285031e-03, -2.31193900e-02,
         -1.62391178e-02,  2.01234706e-02,  1.25450008e-02,
          1.22347362e-02],
        [ 1.87965371e-02,  1.22520924e-02,  4.40502167e-03,
         -1.03689656e-02,  9.05285031e-03, -2.31193900e-02,
         -1.62391178e-02,  2.01234706e-02,  1.25450008e-02,
          1.22347362e-02],
        [ 1.87965371e-02,  1.22520924e-02,  4.40502167e-03,
         -1.03689656e-02,  9.05285031e-03, -2.31193900e-02,
         -1.62391178e-02,  2.01234706e-02,  1.25450008e-02,
          1.22347362e-02],
        [ 2.06583776e-02, -1.98856238e-02, -4.53615300e-02,
          2.04168819e-02, -9.80643183e-03, -7.84134865e-03,
         -1.63927898e-02,  8.11754540e-03,  3.322476